version: '3.1'

# Telegraf, InfluxDB, Chronograf, Kapacitor
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminpassword
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
    external: true
